# Generated by Django 5.0.6 on 2024-06-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Begginer', 'Begginer'), ('Mid-Level', 'Mid-Level'), ('Expert', 'Expert')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
