# Generated by Django 5.0.6 on 2024-06-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_level_course_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Mid-Level', 'Mid-Level'), ('Expert', 'Expert')], max_length=100),
        ),
    ]
